---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths: []
